[versions]
java = "17"
kotlin = "2.4.10"
android_build_tools = "9.3.2"
app_version = "0.0.1"
hilt_version = "2.60.1"
ksp_version = "2.3.11"
coroutine = "1.10.2"
serialization = "1.9.0"
datetime = "0.7.1"

junit = "4.13.2"
androidx-core = "1.19.0"
androidx-appcompat = "1.8.0"
androidx-lifecycle-runtime = "2.11.0"
androidx-lifecycle-viewmodel-compose = "2.11.0"
androidx-activity = "1.13.0"
compose-bom = "2026.08.00"
room = "2.8.4"
navigation-compose = "2.10.0"
navigation-compose-hilt = "1.4.0"
accompanist = "0.32.0"

vico = "1.6.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "android_build_tools" }
android-library = { id = "com.android.library", version.ref = "android_build_tools" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


[libraries]
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
android-hilt-lib = { module = "com.google.dagger:hilt-android", version.ref = "hilt_version" }
android-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt_version" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }
androidx-composeUi = { module = "androidx.compose.ui:ui" }
androidx-composeGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-composeMaterial = { module = "androidx.compose.material:material" }
androidx-composeMaterialIconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-navigation-compose-core = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-compose-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "navigation-compose-hilt" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist"}

serializationx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

vico-core = { module = "com.patrykandpatrick.vico:core", version.ref = "vico"}
vico-compose = { module = "com.patrykandpatrick.vico:compose", version.ref = "vico"}
vico-compose-m3 = { module = "com.patrykandpatrick.vico:compose-m3", version.ref = "vico"}

[bundles]
androidx-compose = ["androidx-composeUi", "androidx-composeGraphics", "androidx-composeMaterial", "androidx-composeUiTooling", "androidx-compose-material3", "androidx-lifecycle-viewmodel-compose"]
accompanist = ["accompanist-systemuicontroller"]
vico = ["vico-core", "vico-compose", "vico-compose-m3"]
