name: Build and Upload Android Release APK
on:
  push:
    branches:
      - main
jobs:
  build_and_upload_apk:
    runs-on: ubuntu-latest
    environment: Build release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Restore key_store file from Base64
        id: decode_key_store
        uses: timheuer/base64-to-file@v1.2
        with:
          encodedString: ${{ secrets.KEY_STORE_FILE_BASE64 }}
          fileName: release.keystore
      - name: Build release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_FILE: ${{ steps.decode_key_store.outputs.filePath }}
      - name: Upload APK and Mapping files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Release
          path: 
            app/build/outputs/apk/release/*.apk
            app/build/outputs/mapping/release/mapping.txt
