name: Build and Upload Android Release APK
on:
  push:
    branches:
      - main
jobs:
  build_and_upload_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Restore key_store file from Base64
        uses: kitek/decode-base64-into-file-action@1.0
        with:
          encoded-value: ${{ secrets.KEY_STORE_FILE_BASE64 }}
          destination-file: release.keystore
      - name: Build release APK
        run: ./gradlew assembleRelease
        env:
          # If you need to provide any environment variables for the build process, you can do so here
          # For example:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      - name: Upload APK and Mapping files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Release
          path: 
            app/build/outputs/apk/release/*.apk
            app/build/outputs/mapping/release/mapping.txt
